#!/bin/bash
# rrd_ipaddress|rrd_service|rrd_function|rrd_time|rrd_value

. .wtrs

in=${WTRS_SPOOL_RAW_CURRENT:?}/latency.txt
out=${WTRS_SPOOL_COOKED:?}/dimension_ip.txt

log "$0: in=$in out=$out"

#string sort on ip address is ugly
#cut -f1 -d'|' $in | sort -u | grep -v rrd_ipaddress > $out

#http://www.sysarch.com/Perl/sort_paper.html

cut -f1 -d'|' $in | perl -e '

die("WTRS_CLIENT_WTID is not set") unless defined($ENV{WTRS_CLIENT_WTID});
my $wtid = $ENV{WTRS_CLIENT_WTID};

while(<>) {
	chomp;
	$ip{$_} = $_;
}

@out = sort {
	pack("C4" => $a =~ /(\d+)\.(\d+)\.(\d+)\.(\d+)/)
	cmp
	pack("C4" => $b =~ /(\d+)\.(\d+)\.(\d+)\.(\d+)/)
} (keys %ip);

for(@out) {
	print "$_|$wtid\n";
}


' > $out
