#!/usr/bin/perl

select(STDOUT);
$| = 1;

while(<>) {
	($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);

	$year += 1900;
	printf("%04d%02d%02d.%02d%02d%02d: ",
		$year,$mon,$mday,
		$hour,$min,$sec);

	print $_;
}
