#!/bin/bash

set -e

host=${1:?}
port=${2:?}
path=${3:?}

echo "${0##*/}: host=$host port=$port path=$path"

go() {
	cat <<EOD
MKCOL ${path:?} HTTP/1.1
Host: ${host:?}:${port:?}

EOD
sleep 1
}

go > /dev/tcp/${host:?}/${port:?}
