#!/bin/bash

# put-file ~/.bash_profile localhost 7308 /u/0.1/23/bar

set -e

filename=${1:?}
host=${2:?}
port=${3:?}
path=${4:?}

if [ ! -f $filename ]
then
	echo "no such file '$filename'"
	exit 1
fi

filesize=`stat --format='%s' ${filename:?}`
echo "${0##*/}: filename=$filename host=$host port=$port path=$path filesize=$filesize"

go() {
	cat <<EOD
PUT ${path:?} HTTP/1.1
Host: ${host:?}:${port:?}
Content-Length: ${filesize:?}

`cat $filename`
EOD

#sleep 2
}

#go > /dev/tcp/${host:?}/${port:?}
go | nc ${host:?} ${port:?}
