#!/bin/bash

. .wtrs-client

rotate client/log

filename=/WT/monitor/etc/datacollection-config.xml
host=${WTRS_CLIENT_HTTPD_HOST:?}
port=${WTRS_CLIENT_HTTPD_PORT:?}
path=/u/${WTRS_CLIENT_BATCHID:?}/${WTRS_CLIENT_WTID:?}/datacollection-config.xml

log "$0: $filename http://$host:$port$path"

put-file $filename $host $port $path
